countries = [# Note had gemini make the first 3 list
    "Albania", "Andorra", "Argentina", "Australia", "Austria", "Bangladesh","Belarus", "Belgium", "Bhutan",
    "Bolivia", "Botswana", "Brazil", "Bulgaria", "Cambodia", "Canada", "Chile", "Colombia", "Costa Rica",
    "Croatia", "Czechia", "Denmark", "Dominican Republic", "Ecuador", "Egypt", "Eswatini", "Estonia", "Finland",
    "France", "Germany", "Ghana", "Greece", "Guatemala", "Hungary", "Iceland", "India", "Indonesia",
    "Ireland", "Israel", "Italy", "Japan", "Kazakhstan", "Kenya", "korea", "Kyrgyzstan", "Laos", "Latvia",
    "Lesotho", "Liechtenstein", "Lithuania", "Luxembourg", "Malaysia", "Malta", "Mexico", "Moldova",
    "Monaco", "Mongolia", "Montenegro", "Morocco", "Myanmar", "Namibia", "Nepal", "Netherlands",
    "New Zealand", "Nigeria", "North Macedonia", "Norway", "Oman", "Panama", "Paraguay", "Peru", 
    "Philippines", "Poland", "Portugal", "Puerto Rico", "Qatar", "Romania", "Russia", "Rwanda", 
    "San Marino", "Senegal", "Serbia", "Singapore", "Slovakia", "Slovenia", "South Africa", "Spain", 
    "Sri Lanka", "Sweden", "Switzerland", "Thailand", "Tunisia", "Turkey", "Uganda", "Ukraine", 
    "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Vietnam"
]

#This is the list of unie words that are used in all of the multi word country names that will be used for sorting
countryWithMultiWordUniqeWords = ['Africa', 'Arab', 'Costa', 'Dominican', 'Emirates', 'Kingdom', 'Lanka', 'Macedonia', 'Marino', 'New', 'North', 'Puerto', 'Republic', 'Rica', 'San', 'South', 'Sri', 'States', 'United', 'Zealand']

continents = {
    "Europe": ["Albania", "Andorra", "Austria","Belarus", "Belgium", "Bulgaria", "Croatia", "Czechia", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg", "Malta", "Moldova", "Monaco", "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal", "Romania", "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", "Ukraine", "United Kingdom"],
    "South America": ["Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Paraguay", "Peru", "Uruguay"],
    "Australia": ["Australia", "New Zealand"],
    "Asia": ["Bangladesh", "Bhutan", "Cambodia", "India", "Indonesia", "Israel", "Japan", "Kazakhstan", "korea", "Kyrgyzstan", "Laos", "Malaysia", "Mongolia", "Myanmar", "Nepal", "Oman", "Philippines", "Qatar", "Singapore", "Sri Lanka", "Thailand", "Turkey", "United Arab Emirates", "Vietnam"],
    "Africa": ["Botswana", "Egypt", "Eswatini", "Ghana", "Kenya", "Lesotho", "Morocco", "Namibia", "Nigeria", "Rwanda", "Senegal", "South Africa", "Tunisia", "Uganda"],
    "North America": ["Canada", "Costa Rica", "Dominican Republic", "Guatemala", "Mexico", "Panama", "Puerto Rico", "United States"]
}

countryBorders = {
    "Albania": ["Greece", "North Macedonia", "Montenegro", "Kosovo"],
    "Andorra": ["France", "Spain"],
    "Argentina": ["Bolivia", "Brazil", "Chile", "Paraguay", "Uruguay"],
    "Australia": [],
    "Austria": ["Czechia", "Germany", "Hungary", "Italy", "Liechtenstein", "Slovakia", "Slovenia", "Switzerland"],
    "Bangladesh": ["India", "Myanmar"],
    "Belarus": ["Russia","Ukraine","Poland"],
    "Belgium": ["France", "Germany", "Luxembourg", "Netherlands","Lithuania","Latvia"],
    "Bhutan": ["China", "India"],
    "Bolivia": ["Argentina", "Brazil", "Chile", "Paraguay", "Peru"],
    "Brazil": ["Argentina", "Bolivia", "Colombia", "French Guiana", "Guyana", "Paraguay", "Peru", "Suriname", "Uruguay", "Venezuela"],
    "Bulgaria": ["Greece", "North Macedonia", "Romania", "Serbia", "Turkey"],
    "Cambodia": ["Laos", "Thailand", "Vietnam"],
    "Canada": ["United States"],
    "Chile": ["Argentina", "Bolivia", "Peru"],
    "Colombia": ["Brazil", "Ecuador", "Panama", "Peru", "Venezuela"],
    "Costa Rica": ["Nicaragua", "Panama"],
    "Croatia": ["Bosnia and Herzegovina", "Hungary", "Montenegro", "Serbia", "Slovenia"],
    "Czechia": ["Austria", "Germany", "Poland", "Slovakia"],
    "Denmark": ["Germany"],
    "Dominican Republic": ["Haiti"],
    "Ecuador": ["Colombia", "Peru"],
    "Egypt": ["Gaza Strip", "Israel", "Libya", "Sudan"],
    "Eswatini": ["Mozambique", "South Africa"],
    "Estonia": ["Latvia", "Russia"],
    "Finland": ["Norway", "Russia", "Sweden"],
    "France": ["Andorra", "Belgium", "Germany", "Italy", "Luxembourg", "Monaco", "Spain", "Switzerland"],
    "Germany": ["Austria", "Belgium", "Czechia", "Denmark", "France", "Luxembourg", "Netherlands", "Poland", "Switzerland"],
    "Ghana": ["Burkina Faso", "Côte d'Ivoire", "Togo"],
    "Greece": ["Albania", "Bulgaria", "North Macedonia", "Turkey"],
    "Guatemala": ["Belize", "El Salvador", "Honduras", "Mexico"],
    "Hungary": ["Austria", "Croatia", "Romania", "Serbia", "Slovakia", "Slovenia", "Ukraine"],
    "Iceland": [],
    "India": ["Bangladesh", "Bhutan", "China", "Myanmar", "Nepal", "Pakistan"],
    "Indonesia": ["East Timor", "Malaysia", "Papua New Guinea"],
    "Ireland": ["United Kingdom"],
    "Israel": ["Egypt", "Jordan", "Lebanon", "Syria"],
    "Italy": ["Austria", "France", "San Marino", "Slovenia", "Switzerland", "Vatican City"],
    "Japan": [],
    "Kazakhstan": ["China", "Kyrgyzstan", "Russia", "Turkmenistan", "Uzbekistan"],
    "Kenya": ["Ethiopia", "Somalia", "South Sudan", "Tanzania", "Uganda"],
    "korea": ["North Korea"],
    "Kyrgyzstan": ["China", "Kazakhstan", "Tajikistan", "Uzbekistan"],
    "Laos": ["Cambodia", "China", "Myanmar", "Thailand", "Vietnam"],
    "Latvia": ["Belarus", "Estonia", "Lithuania", "Russia"],
    "Lesotho": ["South Africa"],
    "Liechtenstein": ["Austria", "Switzerland"],
    "Lithuania": ["Belarus", "Latvia", "Poland", "Russia"],
    "Luxembourg": ["Belgium", "France", "Germany"],
    "Malaysia": ["Brunei", "Indonesia", "Thailand", "Singapore"],
    "Malta": [],
    "Mexico": ["Belize", "Guatemala", "United States"],
    "Moldova": ["Romania", "Ukraine"],
    "Monaco": ["France"],
    "Mongolia": ["China", "Russia"],
    "Montenegro": ["Albania", "Bosnia and Herzegovina", "Croatia", "Kosovo", "Serbia"],
    "Morocco": ["Algeria", "Western Sahara", "Spain"],
    "Myanmar": ["Bangladesh", "China", "India", "Laos", "Thailand"],
    "Namibia": ["Angola", "Botswana", "South Africa", "Zambia"],
    "Nepal": ["China", "India"],
    "Netherlands": ["Belgium", "Germany"],
    "New Zealand": [],
    "Nigeria": ["Benin", "Cameroon", "Chad", "Niger"],
    "North Macedonia": ["Albania", "Bulgaria", "Greece", "Kosovo", "Serbia"],
    "Norway": ["Finland", "Russia", "Sweden"],
    "Oman": ["Saudi Arabia", "United Arab Emirates", "Yemen"], 
    "Panama": ["Colombia", "Costa Rica"],
    "Paraguay": ["Argentina", "Bolivia", "Brazil"],
    "Peru": ["Bolivia", "Brazil", "Chile", "Colombia", "Ecuador"],
    "Philippines": [],
    "Poland": ["Belarus", "Czechia", "Germany", "Lithuania", "Russia", "Slovakia", "Ukraine"],
    "Portugal": ["Spain"],
    "Puerto Rico": [],
    "Qatar": ["Saudi Arabia"], # NEW
    "Romania": ["Bulgaria", "Hungary", "Moldova", "Serbia", "Ukraine"],
    "Russia": ["Azerbaijan", "Belarus", "China", "Estonia", "Finland", "Georgia", "Kazakhstan", "Latvia", "Lithuania", "Mongolia", "North Korea", "Norway", "Poland", "Ukraine"],
    "Rwanda": ["Burundi", "Democratic Republic of the Congo", "Tanzania", "Uganda"],
    "San Marino": ["Italy"],
    "Senegal": ["Gambia", "Guinea", "Guinea-Bissau", "Mali", "Mauritania"],
    "Serbia": ["Bosnia and Herzegovina", "Bulgaria", "Croatia", "Hungary", "Kosovo", "Montenegro", "North Macedonia", "Romania"],
    "Singapore": ["Malaysia"],
    "Slovakia": ["Austria", "Czechia", "Hungary", "Poland", "Ukraine"],
    "Slovenia": ["Austria", "Croatia", "Hungary", "Italy"],
    "South Africa": ["Botswana", "Eswatini", "Lesotho", "Mozambique", "Namibia", "Zimbabwe"],
    "Spain": ["Andorra", "France", "Gibraltar", "Morocco", "Portugal"],
    "Sri Lanka": [],
    "Sweden": ["Finland", "Norway"],
    "Switzerland": ["Austria", "France", "Germany", "Italy", "Liechtenstein"],
    "Thailand": ["Cambodia", "Laos", "Malaysia", "Myanmar"],
    "Tunisia": ["Algeria", "Libya"],
    "Turkey": ["Armenia", "Azerbaijan", "Bulgaria", "Georgia", "Greece", "Iran", "Iraq", "Syria"],
    "Uganda": ["Democratic Republic of the Congo", "Kenya", "Rwanda", "South Sudan", "Tanzania"],
    "Ukraine": ["Belarus", "Hungary", "Moldova", "Poland", "Romania", "Russia", "Slovakia"],
    "United Arab Emirates": ["Oman", "Saudi Arabia"], 
    "United Kingdom": ["Ireland"],
    "United States": ["Canada", "Mexico"],
    "Uruguay": ["Argentina", "Brazil"],
    "Vietnam": ["Cambodia", "China", "Laos"]
}

countryLocation = {# Probibly a better way but hey it works
    "Albania": [[2005,805]],
    "Andorra": [[1952,800,6],[1979,669]],
    "Argentina": [[1760,1038]],
    "Australia": [[2332,1019]],
    "Austria": [[1987,780]],
    "Bangladesh": [[2204,863]],
    "Belarus" : [[2027,748]],
    "Belgium": [[1960,768]],
    "Bhutan": [[2204,852,3],[2214,841]],
    "Bolivia": [[1765,980]],
    "Botswana": [[2012,1000]],
    "Brazil": [[1802,955]],
    "Bulgaria": [[2022,797]],
    "Cambodia": [[2246,898]],
    "Canada": [[1640,752]],
    "Chile": [[1741,1052]],
    "Colombia": [[1736,919]],
    "Costa Rica": [[1709,904]],
    "Croatia": [[1993,787]],
    "Czechia": [[1991,768]],
    "Denmark": [[1822,651]],
    "Dominican Republic": [[1746,879]],
    "Ecuador": [[1725,936]],
    "Egypt": [[2032,854]],
    "Eswatini": [[2037,1012,3],[2042,996]],
    "Estonia": [[2019,726]],
    "Finland": [[2020,706]],
    "France": [[1954,781]],
    "Germany": [[1976,762]],
    "Ghana": [[1949,908]],
    "Greece": [[2011,809]],
    "Guatemala": [[1692,890,3],[1682,824]],
    "Hungary": [[2002,782]],
    "Iceland": [[1891,686]],
    "India": [[2169,867]],
    "Indonesia": [[2272,939]],
    "Ireland": [[1923,751]],
    "Israel": [[2047,837,3],[2047,873]],
    "Italy": [[1986,800]],
    "Japan": [[2341,823]],
    "Kazakhstan": [[2145,776]],
    "Kenya": [[2056,931]],
    "Kyrgyzstan": [[2158,800]],
    "Laos": [[2237,874]],
    "Latvia": [[2021,733]],
    "Lesotho": [[2026,1023,3],[2041,997]],
    "Liechtenstein": [[1976,782,5],[1951,703]],
    "Lithuania": [[2013,743]],
    "Luxembourg": [[1964,769,3],[1974,762]],
    "Malaysia": [[2270,925]],
    "Malta": [[1995,825,5],[1804 ,820]],
    "Mexico": [[1654,866]],
    "Moldova": [[2028,783]],
    "Monaco": [[1969,795,9],[2026,564]],
    "Mongolia": [[2235,785]],
    "Montenegro": [[2003,803,3],[1999,766]],
    "Morocco": [[1930,837]],
    "Myanmar": [[2223,868]],
    "Namibia": [[1995,997]],
    # This is taking so long :(
    "Nepal": [[2184,848]],
    "Netherlands": [[1963,760]],
    "New Zealand": [[2429,1077]],
    "North Macedonia": [[2009,803]],
    "Norway": [[1971,712]],
    "Panama": [[1720,910]],
    "Paraguay": [[1779,998]],
    "Peru": [[1733,962]],
    "Philippines": [[2303,912]],
    "Poland": [[2006,758]],
    "Portugal": [[1924,815]],
    "Puerto Rico": [[1759,882]],
    "Romania": [[2015,784]],
    "Russia": [[2170,719]],
    "Rwanda": [[2035,939]],
    "San Marino": [[1983,796,6],[1,1]],
    "Senegal": [[1908,891]],
    "Serbia": [[2006,792]],
    "Singapore": [[2244,931,6],[2196,904]],
    "Slovakia": [[2002,773]],
    "Slovenia": [[1988,785]],
    "South Africa": [[2012,1027]],
    "korea": [[2311,825]],
    "Spain": [[1935,803]],
    "Sri Lanka": [[2177,912]],
    "Sweden": [[1990,696]],
    "Switzerland": [[1969,782]],
    "Thailand": [[2234,890]],
    "Tunisia": [[1975,828]],
    "Turkey": [[2041,814]],
    "Uganda": [[2039,932]],
    "Ukraine": [[2037,773]],
    "United Kingdom": [[1942,759]],
    "United States": [[1658,807]],
    "Uruguay": [[1786,1032]],
    "United Arab Emirates" :[[2102,864]],
    "Qatar": [[2094,860]],
    "Oman": [[2110,871]],
    "Nigeria": [[1967,906]],
    "Vietnam": [[2254,894]]
}